-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BNQ BenQ GW2790Q ETNAS00854087",
  mode = "2560x1440@100.00",
  position = "-1286x1080",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x162E",
  mode = "1920x1080@144.00",
  position = "1274x1440",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087" })
hl.workspace_rule({ workspace = "3", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Chimei Innolux Corporation 0x162E", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Chimei Innolux Corporation 0x162E" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Chimei Innolux Corporation 0x162E" })
hl.workspace_rule({ workspace = "7", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087" })
hl.workspace_rule({ workspace = "8", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BNQ BenQ GW2790Q ETNAS00854087" })
